//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UJIAN13_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class siswa
    {
        public int id { get; set; }
        public string nama { get; set; }
        public string kelas { get; set; }
        public string jenis_kelamin { get; set; }
    }
}
